In [45]:
# Importing dataset yang telah ditangani (missing value dan outliersnya)
from preprocessing1 import df
from preprocessing1 import df_clean_outliers
from preprocessing1 import df_outliers_replace

## 1. Feature Destructuring

Menambahkan Feature total income yang didapat dari menjumlahkan applicantIncome dan CoapplicantIncome

1. Data asli

In [46]:
df['Total_Income'] = df['ApplicantIncome'] + df['CoapplicantIncome']
col_index = df.columns.get_loc('Loan_Status')

df.insert(col_index, 'Total_Income', df.pop('Total_Income'))

2. Data yang outliernya dihapus

In [47]:
df_clean_outliers['Total_Income'] = df_clean_outliers['ApplicantIncome'] + df_clean_outliers['CoapplicantIncome']
col_index = df_clean_outliers.columns.get_loc('Loan_Status')

df_clean_outliers.insert(col_index, 'Total_Income', df_clean_outliers.pop('Total_Income'))
df_clean_outliers.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,5849.0,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,6091.0,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,3000.0,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,4941.0,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,6000.0,Y

3. Data yang outliernya direplace

In [48]:
df_outliers_replace['Total_Income'] = df_outliers_replace['ApplicantIncome'] + df_outliers_replace['CoapplicantIncome']
col_index = df_outliers_replace.columns.get_loc('Loan_Status')

df_outliers_replace.insert(col_index, 'Total_Income', df_outliers_replace.pop('Total_Income'))

## 2. Encoding

### Data Kategorikal (String)
- Property Area: Urban, Rural, Semiurban  
- Loan Status: Y, N  
- Self Employed: No, Yes  
- Education: Graduate, Not Graduate  
- Married: No, Yes  
- Gender: Male, Female
- Dependents : 0 , 1 , 2 , 3+

Data set asli

In [49]:
df_encoded = df.copy()

# Binary encoding
df_encoded['Gender'] = df_encoded['Gender'].map({'Male': 1, 'Female': 0})
df_encoded['Married'] = df_encoded['Married'].map({'Yes': 1, 'No': 0})
df_encoded['Education'] = df_encoded['Education'].map({'Graduate': 1, 'Not Graduate': 0})
df_encoded['Self_Employed'] = df_encoded['Self_Employed'].map({'Yes': 1, 'No': 0})
df_encoded['Loan_Status'] = df_encoded['Loan_Status'].map({'Y': 1, 'N': 0})
df_encoded['Property_Area'] = df_encoded['Property_Area'].map({'Urban': 1, 'Rural': 2, "Semiurban" : 3})

Dataset yang bersih dari outliers

In [50]:
df_encoded_clean_outliers = df_clean_outliers.copy()

# Binary encoding
df_encoded_clean_outliers['Gender'] = df_encoded_clean_outliers['Gender'].map({'Male': 1, 'Female': 0})
df_encoded_clean_outliers['Married'] = df_encoded_clean_outliers['Married'].map({'Yes': 1, 'No': 0})
df_encoded_clean_outliers['Education'] = df_encoded_clean_outliers['Education'].map({'Graduate': 1, 'Not Graduate': 0})
df_encoded_clean_outliers['Self_Employed'] = df_encoded_clean_outliers['Self_Employed'].map({'Yes': 1, 'No': 0})
df_encoded_clean_outliers['Loan_Status'] = df_encoded_clean_outliers['Loan_Status'].map({'Y': 1, 'N': 0})
df_encoded_clean_outliers['Property_Area'] = df_encoded_clean_outliers['Property_Area'].map({'Urban': 1, 'Rural': 2, "Semiurban" : 3})
df_encoded_clean_outliers['Dependents'].unique()

array([0., 1., 2., 3.])

dataset yang outliersnya direplace

In [51]:
df_encoded_outliers_replace = df_outliers_replace.copy()

# Binary encoding
df_encoded_outliers_replace['Gender'] = df_encoded_outliers_replace['Gender'].map({'Male': 1, 'Female': 0})
df_encoded_outliers_replace['Married'] = df_encoded_outliers_replace['Married'].map({'Yes': 1, 'No': 0})
df_encoded_outliers_replace['Education'] = df_encoded_outliers_replace['Education'].map({'Graduate': 1, 'Not Graduate': 0})
df_encoded_outliers_replace['Self_Employed'] = df_encoded_outliers_replace['Self_Employed'].map({'Yes': 1, 'No': 0})
df_encoded_outliers_replace['Loan_Status'] = df_encoded_outliers_replace['Loan_Status'].map({'Y': 1, 'N': 0})
df_encoded_outliers_replace['Property_Area'] = df_encoded_outliers_replace['Property_Area'].map({'Urban': 1, 'Rural': 2, "Semiurban" : 3})

## Z-score Transformation

Tranformasi data asli

In [52]:
from sklearn.preprocessing import StandardScaler

df_zscore = df_encoded.copy()

scaler = StandardScaler()

num_cols = df_zscore.select_dtypes(include=['int64', 'float64']).columns
num_cols = num_cols.drop('Loan_Status')

df_zscore[num_cols] = scaler.fit_transform(df_zscore[num_cols])

df_zscore.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.472343,-1.372089,-0.737806,0.528362,-0.392601,0.072991,-0.554487,-0.211241,0.273231,0.411733,-1.250298,-0.182184,1
1,LP001003,0.472343,0.728816,0.253470,0.528362,-0.392601,-0.134412,-0.038732,-0.211241,0.273231,0.411733,-0.060092,-0.144684,0
2,LP001005,0.472343,0.728816,-0.737806,0.528362,2.547117,-0.393747,-0.554487,-0.948996,0.273231,0.411733,-1.250298,-0.623656,1
3,LP001006,0.472343,0.728816,-0.737806,-1.892641,-0.392601,-0.462062,0.251980,-0.306435,0.273231,0.411733,-1.250298,-0.322885,1
4,LP001008,0.472343,-1.372089,-0.737806,0.528362,-0.392601,0.097728,-0.554487,-0.056551,0.273231,0.411733,-1.250298,-0.158785,1

Tranformasi Data yng outliernya dihapus

In [53]:
df_zscore_drop = df_encoded_clean_outliers.copy()

scaler = StandardScaler()

num_cols = df_zscore_drop.select_dtypes(include=['int64', 'float64']).columns
num_cols = num_cols.drop('Loan_Status')

df_zscore_drop[num_cols] = scaler.fit_transform(df_zscore_drop[num_cols])

df_zscore_drop.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.483298,-1.347838,-0.709634,0.584183,-0.348829,1.476175,-0.977112,0.068036,0.245281,0.416667,-1.278309,0.391102,1
1,LP001003,0.483298,0.741929,0.306706,0.584183,-0.348829,0.580751,0.082957,0.068036,0.245281,0.416667,-0.082548,0.526873,0
2,LP001005,0.483298,0.741929,-0.709634,0.584183,2.866737,-0.538884,-0.977112,-1.269452,0.245281,0.416667,-1.278309,-1.207290,1
3,LP001006,0.483298,0.741929,-0.709634,-1.711792,-0.348829,-0.833822,0.680475,-0.104543,0.245281,0.416667,-1.278309,-0.118319,1
4,LP001008,0.483298,-1.347838,-0.709634,0.584183,-0.348829,1.582975,-0.977112,0.348477,0.245281,0.416667,-1.278309,0.475819,1

Tranformasi data yang outlaiersnya di replace

In [54]:
df_zscore_replace = df_encoded_outliers_replace.copy()

scaler = StandardScaler()

num_cols = df_zscore_replace.select_dtypes(include=['int64', 'float64']).columns
num_cols = num_cols.drop('Loan_Status')

df_zscore_replace[num_cols] = scaler.fit_transform(df_zscore_replace[num_cols])

df_zscore_replace.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.472343,-1.372089,-0.737806,0.528362,-0.392601,0.461076,-0.912679,-0.211241,0.273231,0.411733,-1.250298,-0.636093,1
1,LP001003,0.472343,0.728816,0.253470,0.528362,-0.392601,1.503416,0.219719,-0.211241,0.273231,0.411733,-0.060092,1.021687,0
2,LP001005,0.472343,0.728816,-0.737806,0.528362,2.547117,-0.637039,-0.912679,-0.948996,0.273231,0.411733,-1.250298,-1.226878,1
3,LP001006,0.472343,0.728816,-0.737806,-1.892641,-0.392601,-1.200887,0.858007,-0.306435,0.273231,0.411733,-1.250298,0.185113,1
4,LP001008,0.472343,-1.372089,-0.737806,0.528362,-0.392601,0.461076,-0.912679,-0.056551,0.273231,0.411733,-1.250298,-0.636093,1

## Logaritma transformation

ori

In [55]:
import numpy as np

df_log = df_encoded.copy()

for col in num_cols:
    df_log[col] = np.log1p(df_log[col])

df_log.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.693147,0.000000,0.000000,0.693147,0.000000,8.674197,0.000000,4.859812,5.888878,0.693147,0.693147,8.674197,1
1,LP001003,0.693147,0.693147,0.693147,0.693147,0.000000,8.430327,7.319202,4.859812,5.888878,0.693147,1.098612,8.714732,0
2,LP001005,0.693147,0.693147,0.000000,0.693147,0.693147,8.006701,0.000000,4.204693,5.888878,0.693147,0.693147,8.006701,1
3,LP001006,0.693147,0.693147,0.000000,0.000000,0.000000,7.857094,7.765993,4.795791,5.888878,0.693147,0.693147,8.505525,1
4,LP001008,0.693147,0.000000,0.000000,0.693147,0.000000,8.699681,0.000000,4.955827,5.888878,0.693147,0.693147,8.699681,1

drop

In [56]:
df_log_drop = df_encoded_clean_outliers.copy()

for col in num_cols:
    df_log_drop[col] = np.log1p(df_log_drop[col])

df_log_drop.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.693147,0.000000,0.000000,0.693147,0.000000,8.674197,0.000000,4.859812,5.888878,0.693147,0.693147,8.674197,1
1,LP001003,0.693147,0.693147,0.693147,0.693147,0.000000,8.430327,7.319202,4.859812,5.888878,0.693147,1.098612,8.714732,0
2,LP001005,0.693147,0.693147,0.000000,0.693147,0.693147,8.006701,0.000000,4.204693,5.888878,0.693147,0.693147,8.006701,1
3,LP001006,0.693147,0.693147,0.000000,0.000000,0.000000,7.857094,7.765993,4.795791,5.888878,0.693147,0.693147,8.505525,1
4,LP001008,0.693147,0.000000,0.000000,0.693147,0.000000,8.699681,0.000000,4.955827,5.888878,0.693147,0.693147,8.699681,1

replace

In [57]:
df_log_replace = df_encoded_outliers_replace.copy()

for col in num_cols:
    df_log_replace[col] = np.log1p(df_log_replace[col])

df_log_replace.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.693147,0.000000,0.000000,0.693147,0.000000,8.246204,0.000000,4.859812,5.888878,0.693147,0.693147,8.246204,1
1,LP001003,0.693147,0.693147,0.693147,0.693147,0.000000,8.430327,7.319202,4.859812,5.888878,0.693147,1.098612,8.714732,0
2,LP001005,0.693147,0.693147,0.000000,0.693147,0.693147,8.006701,0.000000,4.204693,5.888878,0.693147,0.693147,8.006701,1
3,LP001006,0.693147,0.693147,0.000000,0.000000,0.000000,7.857094,7.765993,4.795791,5.888878,0.693147,0.693147,8.505525,1
4,LP001008,0.693147,0.000000,0.000000,0.693147,0.000000,8.246204,0.000000,4.955827,5.888878,0.693147,0.693147,8.246204,1

## Min-max Scaling

ori

In [58]:
from sklearn.preprocessing import MinMaxScaler
df_minmax = df_encoded.copy()

scaler = MinMaxScaler()
df_minmax[num_cols] = scaler.fit_transform(df_minmax[num_cols])

df_minmax.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,1.0,0.0,0.000000,1.0,0.0,0.070489,0.000000,0.172214,0.74359,1.0,0.0,0.055394,1
1,LP001003,1.0,1.0,0.333333,1.0,0.0,0.054830,0.036192,0.172214,0.74359,1.0,0.5,0.058435,0
2,LP001005,1.0,1.0,0.000000,1.0,1.0,0.035250,0.000000,0.082489,0.74359,1.0,0.0,0.019583,1
3,LP001006,1.0,1.0,0.000000,0.0,0.0,0.030093,0.056592,0.160637,0.74359,1.0,0.0,0.043980,1
4,LP001008,1.0,0.0,0.000000,1.0,0.0,0.072356,0.000000,0.191027,0.74359,1.0,0.0,0.057292,1

drop

In [59]:
df_minmax_drop = df_encoded_clean_outliers.copy()

scaler = MinMaxScaler()
df_minmax_drop[num_cols] = scaler.fit_transform(df_minmax_drop[num_cols])
df_minmax_drop.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,1.0,0.0,0.000000,1.0,0.0,0.766716,0.000000,0.370717,0.74359,1.0,0.0,0.434701,1
1,LP001003,1.0,1.0,0.333333,1.0,0.0,0.596394,0.268089,0.370717,0.74359,1.0,0.5,0.458572,0
2,LP001005,1.0,1.0,0.000000,1.0,1.0,0.383425,0.000000,0.177570,0.74359,1.0,0.0,0.153679,1
3,LP001006,1.0,1.0,0.000000,0.0,0.0,0.327324,0.419200,0.345794,0.74359,1.0,0.0,0.345137,1
4,LP001008,1.0,0.0,0.000000,1.0,0.0,0.787031,0.000000,0.411215,0.74359,1.0,0.0,0.449596,1

Replace

In [60]:
df_minmax_replace = df_encoded_outliers_replace.copy()

scaler = MinMaxScaler()
df_minmax_replace[num_cols] = scaler.fit_transform(df_minmax_replace[num_cols])

df_minmax_replace.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,1.0,0.0,0.000000,1.0,0.0,0.623861,0.000000,0.172214,0.74359,1.0,0.0,0.283886,1
1,LP001003,1.0,1.0,0.333333,1.0,0.0,0.858098,0.297788,0.172214,0.74359,1.0,0.5,0.610273,0
2,LP001005,1.0,1.0,0.000000,1.0,1.0,0.377089,0.000000,0.082489,0.74359,1.0,0.0,0.167571,1
3,LP001006,1.0,1.0,0.000000,0.0,0.0,0.250380,0.465640,0.160637,0.74359,1.0,0.0,0.445566,1
4,LP001008,1.0,0.0,0.000000,1.0,0.0,0.623861,0.000000,0.191027,0.74359,1.0,0.0,0.283886,1

## Decimal Scaling

In [61]:
def decimal_scaling(df, cols):
    df_scaled = df.copy()

    for col in cols:
        max_val = df_scaled[col].abs().max()
        j = len(str(int(max_val)))
        df_scaled[col] = df_scaled[col] / (10 ** j)

    return df_scaled

Apply

In [62]:
df_decimal = decimal_scaling(df_encoded, num_cols)
df_decimal_drop = decimal_scaling(df_encoded_clean_outliers, num_cols)
df_decimal_replace = decimal_scaling(df_encoded_outliers_replace, num_cols)

In [63]:
df_decimal.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.1,0.0,0.0,0.1,0.0,0.05849,0.00000,0.128,0.36,0.1,0.1,0.05849,1
1,LP001003,0.1,0.1,0.1,0.1,0.0,0.04583,0.01508,0.128,0.36,0.1,0.2,0.06091,0
2,LP001005,0.1,0.1,0.0,0.1,0.1,0.03000,0.00000,0.066,0.36,0.1,0.1,0.03000,1
3,LP001006,0.1,0.1,0.0,0.0,0.0,0.02583,0.02358,0.120,0.36,0.1,0.1,0.04941,1
4,LP001008,0.1,0.0,0.0,0.1,0.0,0.06000,0.00000,0.141,0.36,0.1,0.1,0.06000,1

In [64]:
df_decimal_drop.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.1,0.0,0.0,0.1,0.0,0.5849,0.0000,0.128,0.36,0.1,0.1,0.05849,1
1,LP001003,0.1,0.1,0.1,0.1,0.0,0.4583,0.1508,0.128,0.36,0.1,0.2,0.06091,0
2,LP001005,0.1,0.1,0.0,0.1,0.1,0.3000,0.0000,0.066,0.36,0.1,0.1,0.03000,1
3,LP001006,0.1,0.1,0.0,0.0,0.0,0.2583,0.2358,0.120,0.36,0.1,0.1,0.04941,1
4,LP001008,0.1,0.0,0.0,0.1,0.0,0.6000,0.0000,0.141,0.36,0.1,0.1,0.06000,1

In [65]:
df_decimal_replace.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_Status
0,LP001002,0.1,0.0,0.0,0.1,0.0,0.381213,0.0000,0.128,0.36,0.1,0.1,0.381213,1
1,LP001003,0.1,0.1,0.1,0.1,0.0,0.458300,0.1508,0.128,0.36,0.1,0.2,0.609100,0
2,LP001005,0.1,0.1,0.0,0.1,0.1,0.300000,0.0000,0.066,0.36,0.1,0.1,0.300000,1
3,LP001006,0.1,0.1,0.0,0.0,0.0,0.258300,0.2358,0.120,0.36,0.1,0.1,0.494100,1
4,LP001008,0.1,0.0,0.0,0.1,0.0,0.381213,0.0000,0.141,0.36,0.1,0.1,0.381213,1

## Dataset Hasil Preprocessing dan Transformasi

Pada tahap ini dihasilkan beberapa dataset dari kombinasi penanganan outliers dan teknik transformasi data:

### 1. Dataset Original (tanpa penanganan outliers)
- `df_encoded` → data hasil encoding
- `df_zscore` → transformasi Z-score
- `df_log` → transformasi logaritma
- `df_minmax` → transformasi Min-Max
- `df_decimal` → transformasi decimal scaling

### 2. Dataset dengan Outliers Dihapus
- `df_encoded_clean_outliers`
- `df_zscore_drop`
- `df_log_drop`
- `df_minmax_drop`
- `df_decimal_drop`

### 3. Dataset dengan Outliers di-Replace (Median)
- `df_encoded_outliers_replace`
- `df_zscore_replace`
- `df_log_replace`
- `df_minmax_replace`
- `df_decimal_replace`

Semua dataset ini digunakan untuk membandingkan performa model dalam berbagai kondisi preprocessing dan transformasi.

In [66]:
df_zscore_drop.info()

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            507 non-null    str
 1   Gender             507 non-null    float64
 2   Married            507 non-null    float64
 3   Dependents         507 non-null    float64
 4   Education          507 non-null    float64
 5   Self_Employed      507 non-null    float64
 6   ApplicantIncome    507 non-null    float64
 7   CoapplicantIncome  507 non-null    float64
 8   LoanAmount         507 non-null    float64
 9   Loan_Amount_Term   507 non-null    float64
 10  Credit_History     507 non-null    float64
 11  Property_Area      507 non-null    float64
 12  Total_Income       507 non-null    float64
 13  Loan_Status        507 non-null    int64
dtypes: float64(12), int64(1), str(1)
memory usage: 55.6 KB